version: "2.4"
services:
  workspace:
    container_name: parallel-wave-gan-workspace
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: "32gb"
    runtime: nvidia
    user: root
    tty: true
    volumes:
      - .:/workspace
      - /opt/storage:/opt/storage
    environment:
      GRANT_SUDO: "yes"
      PYTHONPATH: /workspace
  jupyter:
    container_name: parallel-wave-gan-jupyter
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    user: root
    ports:
      - "9300:8888"
    volumes:
      - .:/workspace
      - /opt/storage:/opt/storage
    environment:
      GRANT_SUDO: "yes"
    command: jupyter lab --allow-root --config=/root/.jupyter/jupyter_notebook_config.py

networks:
  default:
    ipam:
      config:
        - subnet: 172.168.215.0/24
